#!/usr/bin/env python
import os
import time
import random

def check(key):
	sum = 0
	for c in key:
		sum += ord(c)
	return sum

completed = False
key = ""
while True:
	keyPluggedIn = os.path.isdir("/Volumes/ESD-USB")
	if keyPluggedIn:
		time.sleep(0.75)
		while not completed:	
				key += random.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+{[]|:,<.>/?~")
				sum = check(key)
				if sum > 867:
					key = ""
				elif sum == 867:
					os.popen("echo \"" + key + "\" > /Volumes/ESD-USB/key.txt")
					if check(os.popen("cat /Volumes/ESD-USB/key.txt").read().rstrip()) == 867:
						completed = True
		break
	else:
		time.sleep(0.5)